name: llm-corpus-audit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - nltk>=3.8.1
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyterlab>=4.0.0
  - notebook>=7.0.0
  - pip:
    - spacy>=3.7.0
    - spacy-llm>=0.1.0
    - lexicalrichness>=0.1.0
    - textstat>=0.7.3
    - wordcloud>=1.9.0
    - scattertext>=0.1.0
    - plotly>=5.18.0
    - transformers>=4.36.0
    - accelerate>=0.25.0
    - sentencepiece>=0.1.99
    - datasets>=2.16.0
    - evaluate>=0.4.0
    - huggingface_hub>=0.20.0
    - label-studio==1.11.0
    - openai>=1.0.0
    - tiktoken>=0.5.0
    - google-api-python-client>=2.0.0  # For Perspective API 